const String kOtraColonia = 'Otra (escribir)';

const Map<String, List<String>> kColimaColoniasByZip = {
  '28000': ['Colima Centro'],
  '28010': ['Lomas de Circunvalación', 'Militar Lomas'],
  '28014': ['Jardines de las Lomas'],
  '28016': ['Lomas Vistahermosa'],
  '28017': [
    'Bugambilias',
    'Colinas de Santa Bárbara',
    'Jardines Vista Hermosa',
    'Las Palmas',
    'Lomas Verdes',
    'Parque Royal',
    'Residencial Santa Bárbara',
    'Lomas del Valle',
    'Residencial Valle Verde',
    'Rincón del Colibrí',
    'Bosque de la Cantera',
    'Albaterra Residencial',
    'El Volantín',
    'Residencial La Primavera',
    'Residencial Romanza',
    'El Roble Residencial',
    'Residencial Puerta del Sol',
    'Residencial Esmeralda',
    'Villanova',
    'Privada San Rafael',
    'Villas Colinas',
    'Residencial Esmeralda Norte',
    'Residencial Los Olivos',
    'Jardines de La Hacienda',
    'Residencial Real Santa Bárbara',
    'Residencial Victoria',
    'Paseo de la Hacienda',
    'Colinas de Santa Fe',
    'Paseo de la Cantera',
    'Santa Gertrudis',
    'Punta Norte',
  ],
  '28018': [
    'El Diezmo',
    'Hacienda Real',
    'Loredo Residencial',
    'Real Vista Hermosa',
    'Girasoles',
    'Valle Dorado',
    'Puerta Paraíso',
    'La Cantera',
    'Las Pérgolas',
    'Residencial Santa María',
  ],
  '28019': ['El Porvenir', 'Puerta del Camino Real'],
  '28020': ['La Armonía', 'Jardines de Guadalupe'],
  '28025': ['Niños Héroes', 'Villa los Prados'],
  '28030': [
    'Guadalajarita',
    'Jardines de La Corregidora',
    'Jardines Residenciales',
    'Magisterial',
    'Morelos',
  ],
  '28035': ['Huertas del Sol'],
  '28037': ['Hidalgo'],
  '28040': [
    'Camino Real',
    'INFONAVIT La Estancia',
    'Las Víboras',
    'Burócratas',
  ],
  '28043': ['INFONAVIT Camino Real'],
  '28044': ['FOVISSSTE'],
  '28045': ['Villa San Sebastián'],
  '28046': ['Oriental'],
  '28047': [
    'Lomas de Santa Elena',
    'Villa de los Pinos',
    'Andares del Jazmín',
    'Camino Real',
    'Francisco I Madero',
    'Jardines de La Estancia',
    'Josefa Ortiz de Domínguez',
    'La Virgencita',
    'Lázaro Cárdenas',
    'Luis Donaldo Colosio',
    'Revolución',
    'San José Norte',
    'Rivera del Jazmín',
    'Real la Floresta',
    'IKAL',
    'Santa Elena',
    'Las Américas',
    'Unidad Antorchista',
    'El Mirador de Colima',
    'Diamantes',
    'Margaritas',
  ],
  '28048': [
    'Cuauhtémoc',
    'El Pedregal',
    'Insurgentes',
    'La Estancia',
    'La Guadalupe',
    'Los Ángeles',
    'Moctezuma',
    'Nuevo Paraíso',
    'Paraíso',
    'San José Sur',
    'San Rafael',
    'Santa Amalia',
    'Vicente Guerrero',
    'Milenio IV',
    'Cardona',
    'Jardines del Sol',
    'Nuevo Milenio',
    'Mirador de La Cumbre',
    'Gustavo Vázquez Montes',
    'Los Jazmines',
    'Mirador de La Cumbre II',
    'Mirador de La Cumbre III',
    'Ignacio Zaragoza',
  ],
  '28050': [
    'Fátima',
    'Placetas Estadio',
    'Villas del Bosque',
    'Villas Primaveras',
    'Rincón del Bosque',
    'Privada San Francisco',
  ],
  '28060': ['El Moralete', 'Residencial San Pablo'],
  '28063': [
    'Francisco Villa',
    'Santa Gertrudis',
    'Las Haciendas',
    'Los Volcanes',
    'Rinconada San Pablo',
    'San Carlos',
  ],
  '28067': ['De los Trabajadores'],
  '28070': ['Los Viveros', 'Del Periodista', 'Popular', 'Patios de Ferrocarril'],
  '28075': ['Parque Industrial', 'Hacienda El Balcón'],
  '28077': ['Rinconada del Pereyra', 'Arboledas', 'José Pimentel Llerenas'],
  '28078': [
    'Benito Juárez',
    'INDECO Albarrada',
    'Jardines de las Fuentes',
    'El Torreón',
    'Residencial Prados del Sur',
    'El Yaqui',
    'Las Fuentes',
    'La Rivera',
    'Valle Real',
    'Arboledas de La Hacienda',
    'La Albarrada',
    'Real de Don Juan',
    'El Prado',
  ],
  '28079': [
    'Gregorio Torres Quintero',
    'Puerta del Valle',
    'Villas del Sur',
    'Parajes del Sur',
  ],
  '28080': ['El Tivoli'],
  '28085': ['Juana de Asbaje', 'Hacienda el Alpuyeque', 'Los Sauces'],
  '28089': ['Leonardo B Gutiérrez', 'Quinta El Tívoli', 'Bosques del Sur'],
  '28090': [
    'El Tecolote',
    'Francisco Zaragoza Vázquez',
    'San Germán',
    'La Esperanza',
    'Las Bugambilias',
  ],
  '28600': [
    'Estapilla',
    'Piscila',
    'Puerta de Ánzar',
    'Los Tepames',
    'Ticuizitán',
    'Tinajas',
    'El Amarradero',
    'La Higuerita',
  ],
  '28610': ['San Ángel Residencial', 'El Chanal'],
  '28613': ['La Capacha'],
  '28620': ['Lo de Villa', 'Ejidal', 'J Jesús Ríos'],
  '28626': ['El Alpuyequito', 'Loma de Fátima'],
  '28627': ['Loma de Juárez (El Mezquite)'],
  '28628': ['Los Mezcales'],
  '28629': ['Las Golondrinas'],
  '28634': [
    'Corralitos',
    'El Astillero de Abajo',
    'El Astillero de Arriba',
    'Trapichillos',
    'El Bordo',
    'La Media Luna',
  ],
  '28635': ['Paso del Zarco', 'La Loma de Ignacio Allende'],
  '28640': ['Nuevo', 'Los Asmoles'],
  '28645': ['Acatitán'],
  '28646': ['Las Guásimas (Las Borregas)'],
  '28647': ['Los Ortices'],
  '28656': ['Las Tunas'],
  '28950': ['Juluapan'],
  '28952': ['Los Picachos'],
  '28955': ['Agua Dulce'],
  '28958': ['El Mixcuate'],
  '28959': ['Pueblo Nuevo'],
  '28960': ['El Carrizal'],
  '28963': ['Pastores'],
  '28965': ['Las Joyitas', 'El Chivato (Providencia)', 'La Montrica'],
  '28968': ['El Nuevo Naranjal', 'El Naranjal'],
  '28970': ['Villa de Álvarez Centro', 'Villas del Sol'],
  '28973': [
    'Floresta',
    'Manuel M. Diéguez',
    'Real los Arcos',
    'Santa Teresa',
    'Villas del Río',
    'Villas Adriana',
    'Villas de Mayo',
    'Santa Cristina',
    'Privada Villa San Agustín',
    'Rancho Santo',
  ],
  '28974': ['Las Palomas Residencial', 'San Isidro', 'Villas Coliman'],
  '28975': [
    'López Mateos',
    'Santa Martha',
    'Morelos',
    'Villa Carlo',
    'La Frontera',
    'La Cajita del Agua',
    'Privada Villas del Palmar',
  ],
  '28976': [
    'Liberación',
    'Villas del Centro',
    'Francisco Hernández',
    'Rosario Ibarra de Piedra',
  ],
  '28977': ['Las Parotas'],
  '28978': [
    'Residencial Bosque Real',
    'Real de Caná',
    'Colinas del Real',
    'Arboledas del Carmen',
    'Azaleas',
    'Colinas del Carmen',
    'FOVISSSTE',
    'Golondrinas',
    'Jardines de Bugambilias',
    'Primaveras',
    'Rinconada de La Hacienda',
    'Senderos del Carmen',
    'Real Hacienda',
    'Real Santa Fe',
    'Hacienda del Carmen',
  ],
  '28979': [
    'Colinas de las Lagunas',
    'Alfredo V. Bonfil',
    'Las Águilas',
    'Lindavista',
    'Lomas de las Flores',
    'Loma Hermosa',
    'Lomas de La Higuera',
    'Los Almendros',
    'Solidaridad',
    'Villa Izcalli Caxitlán',
    'Villas de Bugambilias',
    'Real Bugambilias',
    'Carlos de La Madrid',
    'Lomas Altas',
    'Villas del Cañaveral',
    'El Angel',
    'Cruz de Comala',
    'Lomas de La Villa',
    'Vista Bugambilias',
    'Bugambilias',
    'Las Colinas',
    'Las Lagunas',
    'Lomas de La Herradura',
    'Residencial Colinas del Rey',
    'Salomón Preciado',
    'Colinas del Sol',
  ],
  '28980': ['La Gloria'],
  '28982': [
    'Villas San José Segunda Sección',
    'Villas de Alameda',
    'La Joya',
    'El Cortijo',
    'Santa Fe',
    'Los Olivos',
    'Jacarandas',
    'Hacienda El Nogal',
    'Hacienda del Cortijo',
    'Las Rosas',
  ],
  '28983': [
    'Valle del Sol',
    'Puerta Higueras',
    'Las Presas',
    'Rinconada del Centenario',
    'Jardines del Centenario',
    'Alfonso Rolón Michel',
    'Tabachines',
    'Senderos de Rancho Blanco',
    'Villa Flores',
    'Villas Rancho Blanco',
    'El Haya',
    'Puerta de Rolón',
    'Residencial Tulipanes',
    'Villa Flores II',
  ],
  '28984': [
    'Patria Residencial',
    'Palo Alto',
    'Villafuentes',
    'Punta Diamante Residencial',
    'Residencial Los Robles',
    'Vista Volcanes',
    'La Fortuna',
    'Real del Seis',
    'La Esperanza',
    'Real del Siete',
    'Benito Juárez',
    'Azteca',
    'El Centenario',
    'Juan José Ríos',
    'Loma Bonita',
    'Lomas del Centenario',
    'Manuel Álvarez',
    'Ramón Serrano',
    'Real Centenario',
    'Villas de San José',
    'Jardines de La Villa',
    'Los Triángulos',
    'Puerta del Centenario',
    'Centenario II',
    'La Reserva',
    'Buenavista',
    'Verde Valle',
    'Higueras del Espinal',
  ],
  '28985': ['Del Valle', 'Villa de Oro', 'San Miguel'],
  '28986': ['Residencial Santa Sofía', 'Emiliano Zapata', 'Villas Diamante'],
  '28987': ['Alta Villa', 'La Haciendita', 'San Carlos', 'Villas Providencia'],
  '28988': ['Real de San Jorge', 'Campestre', 'El Llano'],
  '28989': [
    'Montellano',
    'Ciudad Natura',
    'Montellano II',
    'Acueducto Residencial',
    'Micro Parque Industrial',
    'Burócratas del Estado',
    'Las Tunas',
    'Leandro Valle',
    'Prados de La Villa',
    'Villa de Alba',
    'Jardines del Llano',
    'Puerta de Hierro',
    'Campestre Bugambilias',
    'Real de Minas',
    'La Comarca',
  ],
};

List<String> coloniasForZip(String zip) {
  final code = zip.trim();
  if (code.isEmpty) return const [];
  final list = List<String>.from(kColimaColoniasByZip[code] ?? const []);
  list.sort();
  list.add(kOtraColonia);
  return list;
}
